"""empty message

Revision ID: 4c2a1e52d1df
Revises: c2ef298168a6
Create Date: 2021-03-16 23:32:57.103658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2a1e52d1df'
down_revision = 'c2ef298168a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'domain')
    # ### end Alembic commands ###
