"""empty message

Revision ID: 79286b0dd415
Revises: fa772e051e34
Create Date: 2021-04-03 22:12:38.458054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79286b0dd415'
down_revision = 'fa772e051e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('fcm_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'fcm_token')
    # ### end Alembic commands ###
