"""empty message

Revision ID: aeb699c69ba9
Revises: b57384eeab55
Create Date: 2021-03-16 23:57:49.296365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeb699c69ba9'
down_revision = 'b57384eeab55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('innertext', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'innertext')
    # ### end Alembic commands ###
