"""empty message

Revision ID: b57384eeab55
Revises: 4c2a1e52d1df
Create Date: 2021-03-16 23:41:02.944617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57384eeab55'
down_revision = '4c2a1e52d1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'deleted_at')
    # ### end Alembic commands ###
