version: "3.3"

services:
  ls_api:
    build: .
    ports:
      - "5001:8000"
    command: >
      sh -c "gunicorn -b 0.0.0.0:8000 production:app"
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - /www/linkstorage_images:/usr/src/images
      - /www/cert:/usr/cert